version: "3.7"
services:
  db:
    image: "mariadb:10.7.3"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_sync:/var/lib/mysql:nocopy
    environment:
      MARIADB_ROOT_PASSWORD: "db"
      MARIADB_DATABASE: "iptvhandler"
      MARIADB_USER: "db"
      MARIADB_PASSWORD: "db"
    logging:
      driver: none
    networks:
      - iptvhandler
    healthcheck:
      test: "mysql iptvhandler -udb -pdb -e 'SELECT 1;'  || exit 1"
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 30
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    command: >
      bash -c "sqlx database drop -y && 
               sqlx database create && 
               sqlx migrate run"
    networks:
      - iptvhandler
    restart: "no"
    env_file: ./src/.env
    volumes:
      - ./src/db/migrations:/init/migrations
    depends_on:
      db:
        condition: service_healthy
  server:
    build:
      context: .
      dockerfile: Dockerfile.develop
    command: >
      bash -c "cargo sqlx prepare -- --manifest-path ./db/Cargo.toml --lib &&
               cargo build && 
               cargo watch -x run"
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - server_sync:/usr/src/app:nocopy # docker-sync to speed up slow compiles
    env_file: ./src/.env
    networks:
      - iptvhandler
    depends_on:
      migration:
        condition: "service_completed_successfully"
volumes:
  server_sync:
    external: true
  db_sync:
    external: true
networks:
  iptvhandler:
    name: iptvhandler
