version: "3.8"
services:
  gui:
    build:
      context: "./gui"
      dockerfile: Dockerfile
    networks:
      - iptvproxy
    volumes:
      - gui_sync:/app/src:nocopy
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.develop
    ports:
      - "3001:3001"
    volumes:
      - server_sync:/usr/src/app:nocopy # docker-sync to speed up slow compiles
    env_file: ./server/.env
    environment:
      M3U: "https://iptv-org.github.io/iptv/countries/se.m3u"
    command: bash -c "/wait-for-it.sh db:3306 -q -- cargo watch -x run"
    depends_on:
      - db
    networks:
      - iptvproxy
  db:
    image: "mariadb:latest"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_sync:/var/lib/mysql:nocopy
    environment:
      MYSQL_ROOT_PASSWORD: "db"
      MYSQL_DATABASE: "iptvproxy"
      MYSQL_USER: "db"
      MYSQL_PASSWORD: "db"
    networks:
      - iptvproxy
volumes:
  server_sync:
    external: true
  db_sync:
    external: true
  gui_sync:
    external: true
networks:
  iptvproxy:
    name: iptvproxy
