version: "3.7"
services:
  db:
    image: "mariadb:10.7.3"
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "db"
      MARIADB_DATABASE: "iptvhandler"
      MARIADB_USER: "db"
      MARIADB_PASSWORD: "db"
    logging:
      driver: none
    networks:
      - iptvhandler
    healthcheck:
      test: "mysql iptvhandler -udb -pdb -e 'SELECT 1;' || exit 1"
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 30
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    command: >
      bash -c "sqlx database drop -y &&
               sqlx database create &&
               sqlx migrate run &&
               cargo sqlx prepare -- --lib"
    networks:
      - iptvhandler
    env_file: ./.env
    volumes:
      - ./src:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
  server:
    build:
      context: .
      dockerfile: Dockerfile.develop
    command: cargo watch --delay 4 --why -x run
    tty: true # color terminal output
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app
    env_file: ./.env
    networks:
      - iptvhandler
    depends_on:
      migration:
        condition: "service_completed_successfully"
volumes:
  db:
    external: false
networks:
  iptvhandler:
    name: iptvhandler
