
FROM lukemathwalker/cargo-chef:0.1.35-rust-1.61-slim-bullseye as chef

FROM chef AS planner
COPY ./src .

RUN apt update && \ 
    apt install pkg-config -y && \
    apt install libssl-dev -y

RUN cargo chef prepare --recipe-path recipe.json
RUN cargo chef cook --recipe-path recipe.json

RUN cargo install cargo-watch
RUN cargo install sqlx-cli --no-default-features --features rustls,mysql

WORKDIR /usr/src/app

EXPOSE 3001

VOLUME ["/usr/local/cargo"]