FROM rust:1.61-slim-bullseye

RUN apt update && \ 
    apt install pkg-config -y && \
    apt install libssl-dev -y

RUN cargo install sqlx-cli --no-default-features --features rustls,mysql

WORKDIR /usr/src/app/db