version: "3.7"
services:
  server:
    image: WIP
    entrypoint: cargo run
    tty: true # color terminal output
    ports:
      - "3001:3001"
    env_file: ./src/.env
    networks:
      - iptvhandler
networks:
  iptvhandler:
    name: iptvhandler
