version: "2.4"
services:
  db:
    image: "mariadb:10.7.3"
    restart: always
    # command: mariadb
    ports:
      - 3306:3306
    volumes:
      - db_sync:/var/lib/mysql:nocopy
    environment:
      MARIADB_ROOT_PASSWORD: "db"
      MARIADB_DATABASE: "iptvhandler"
      MARIADB_USER: "db"
      MARIADB_PASSWORD: "db"
    logging:
      driver: none
    networks:
      - iptvhandler
  migration:
    build:
      context: ./db
    command: bash -c "./wait-for-it.sh db:3306 -- sqlx database drop -y && sqlx database create && sqlx migrate run"
    depends_on:
      - db
    networks:
      - iptvhandler
    restart: "no"
    env_file: ./server/.env
    volumes:
      - ./server/db/migrations:/init/migrations
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.develop
    command: bash -c "( cd db ; touch ./src/lib.rs && cargo sqlx prepare -- --lib ) && cargo watch -x run"
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - server_sync:/usr/src/app:nocopy # docker-sync to speed up slow compiles
    env_file: ./server/.env
    environment:
      PORT: 3001
      RUST_LOG: warn,server=warn,iptv=info,api=warn,rest-client=warn

      M3U: "https://iptv-org.github.io/iptv/countries/se.m3u"
    depends_on:
      - db
    networks:
      - iptvhandler
volumes:
  server_sync:
    external: true
  db_sync:
    external: true
networks:
  iptvhandler:
    name: iptvhandler
