CREATE TABLE IF NOT EXISTS Provider (
    id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` TEXT NOT NULL,
    source TEXT NOT NULL,
    groups TEXT NOT NULL,
    channels TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS M3U (
    id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` TEXT NOT NULL,
    source TEXT NOT NULL,
    groups TEXT NOT NULL,
    channels TEXT NOT NULL
);