
# Rust as the base image
FROM lukemathwalker/cargo-chef:latest-rust-1.53.0 AS chef

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

RUN cargo chef cook --recipe-path recipe.json
RUN cargo install cargo-watch

WORKDIR /usr/src/app

EXPOSE 3001

VOLUME ["/usr/local/cargo"]