[package]
name = "iptv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
m3u = "1.0.0"
rest-client = { path = "../rest-client" }
